### ISSUE TITLE
Cannot compile 64 bit programs

### ISSUE THREAD

**Issue by xhgzs** [cheat-engine/cheat-engine#1362]
![1](https://user-images.githubusercontent.com/51228394/93737335-83903400-fc15-11ea-9772-d07cff7cc0b9.png)
I downloaded the 64 bit FPC, but still can't compile the 64 bit program. Lazarus FPC is shown in the figure below
![2](https://user-images.githubusercontent.com/51228394/93737399-af131e80-fc15-11ea-8880-64ab028cf642.png)

**Comment by xhgzs** [comment]
**Compile Project, Mode: Release 64-Bit, Target: bin\cheatengine-x86_64.exe: Exit code 1, Errors: 3, Warnings: 2
networkConfig.pas(163,21) Warning: range check error while evaluating constants (843788 must be between 0 and 65535)
networkConfig.pas(171,24) Warning: range check error while evaluating constants (843788 must be between 0 and 65535)
PEInfounit.pas(247,42) Error: identifier idents no member "BaseOfData"
PEInfounit.pas(449,91) Error: identifier idents no member "BaseOfData"
PEInfounit.pas(453,108) Error: identifier idents no member "BaseOfData"**
![3](https://user-images.githubusercontent.com/51228394/93739050-e8e62400-fc19-11ea-9529-60b9525e58ad.png)

**Comment by mgrinzPlayer** [comment]
Duplicate of #1308.

Requirements:
- download and install **lazarus-2.0.10-fpc-3.2.0-win32.exe**
- download and install **lazarus-2.0.10-fpc-3.2.0-cross-x86_64-win64-win32.exe**
- use recent source files from this repository ( or apply changes from this commit https://github.com/cheat-engine/cheat-engine/commit/b108ae3922f0350da3bd9a38e1f6c122342179d3 )

**Comment by xhgzs** [comment]
The problem is solved. Thank you

**Comment by Skoobary** [comment]
![image](https://github.com/cheat-engine/cheat-engine/assets/83435558/6d10cc55-cf7f-49ac-945d-c2bd195497bf)
downloaded both versions of lazarus but still getting this error when i try to compile the 64bit version

**Comment by fade2gray** [comment]
You are using the incorrect version of Lazarus - try reading the build instructions again.

https://github.com/cheat-engine/cheat-engine#basic-build-instructions

![Screenshot 2024-01-18 164529](https://github.com/cheat-engine/cheat-engine/assets/1332009/f15d44a8-1c6c-49c6-ad29-f8c614b35afe)

**Use Lazarus 2.2.2 or Lazarus 2.2.6.**
